### ISSUE TITLE
Setting up for Zenodo

### ISSUE THREAD

**Issue by LinguList** [pano-tacanan-history/trimming-paper#2]
To set this up for Zenodo, it is best if I retain the right to modify the metadata, so I can add Grant information. So the zenodofication would then be left to me, once we have decided that this is the "final" version. Versions will be made after this decision, and after I have set up the integration with Zenodo (on Wednesday).

**Comment by FredericBlum** [comment]
As you are co-owner of "pano-tacanan-history", you should have that right already. Is that not the case?

**Comment by LinguList** [comment]
Yes. I just wanted to make sure you don't hit the "submit new release" button before I have wired it up ;)

**Comment by FredericBlum** [comment]
I've updated the release to include lingreg and checked that it runs in a fresh venv. The new doi: 10.5281/zenodo.7780719 

Do you need to update something or can I update the release with the Zenodo link already, to finalize the release?

**Comment by LinguList** [comment]
You can already replace it. I need to look into the metadata later. But that is independent.

**Comment by FredericBlum** [comment]
Ok perfect, the release is now updated.

**Comment by LinguList** [comment]
Cool, I just saw: metadata are preserved.
